local dir = 'plugin'
require(dir .. '/lua-line')
require(dir .. '/nvim-cmp')
require(dir .. '/tree-sitter')
require(dir .. '/indent-line')
require(dir .. '/nvim-tree')
require(dir .. '/autopairs')
require(dir .. '/gitsigns')
require(dir .. '/zk')
require(dir .. '/lua-snip')
