#!/bin/sh
# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Change default config and data directories of these programs
export LEIN_HOME="$XDG_DATA_HOME"/lein
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export GTK_RC_FILES="$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

export GTK_IM_MODULE='ibus'
export QT_IM_MODULE='ibus'
export XMODIFIERS=@im='ibus'

# Environment Variables
export ZDOTDIR="$HOME/.config/zsh"
export EDITOR=hx
export TERMINAL=alacritty
export WASMTIME_HOME="$HOME/.wasmtime"
export BROWSER=firefox
export HISTCONTROL=ignoreboth
export MANROFFOPT='-c'
export FZF_DEFAULT_OPTS="--layout=reverse --height=5%"
export ROFI_PLUGIN_PATH="$HOME/.local/lib/rofi-plugins"

export BAT_PAGER="less -iRI"
export MANPAGER="sh -c 'col -bx | bat --paging always -l man -p'"

export DOTFILES="$HOME/.dotfiles"
export SUDO_ASKPASS="$DOTFILES/bin/askpass.sh"
export LC_ALL=en_US.UTF-8
export GTK_THEME=Adwaita:dark
export LIBVIRT_DEFAULT_URI="qemu:///system"
export VIRSH_DEFAULT_CONNECT_URI="qemu:///system"
export MAILCHECK=""

export ODIN_ROOT="$HOME/.local/bin/odin"
export PATH="$PATH:/usr/sbin:$HOME/.local/bin:$DOTFILES/bin:$ODIN_ROOT:$WASMTIME_HOME/bin:$HOME/.nix-profile/bin"

export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

export XCURSOR_SIZE=24
export XCURSOR_THEME=breeze_cursors
export DXVK_FRAME_RATE=144
