#!/bin/sh

if command -v opam > /dev/null; then
    eval $(opam env)
fi

# Start graphical server on user's current tty if not already running.
# exec startx "$XINITRC"
# if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ] && [ -z "$TMUX" ]; then
#     export MOZ_ENABLE_WAYLAND=1
#     if [ -e "/sys/class/power_supply/BAT0" ]; then
#         exec Hyprland --config ~/.config/hypr/laptop.conf
#     else
#         exec Hyprland --config ~/.config/hypr/desktop.conf
#     fi
# fi

# export WLR_RENDERER=vulkan
if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ] && [ -z "$TMUX" ]; then
    export MOZ_ENABLE_WAYLAND=1

    if [ -e "/sys/class/power_supply/BAT0" ]; then
        exec sway --config ~/.config/sway/laptop
    else
        exec sway --config ~/.config/sway/desktop
    fi
fi
