#!/bin/sh

set-keyboar-settings.sh &
redshift -PO 5000 &
# wait for the WM to start before running
while true; do
  if pgrep awesome > /dev/null; then
    sleep 0.2
    sxhkd &
    pgrep nextcloud || nextcloud & disown
    # dunst &
    # dwm-status &
    break
  fi
done &

# Start WM
exec awesome
