#!/bin/sh
# WM/DE independant autostart
setxkbmap -layout 'us,ar' -option 'grp:alt_shift_toggle' &
xset r rate 250 40
change-wallpaper.sh &
redshift -PO 5000 &
# start-picom.sh &
# dunst &
# wait for the WM to start before running
while true; do
  if pgrep awesome > /dev/null; then
    sleep 0.2
    # ~/.config/polybar/start-polybar.sh &
    sxhkd &
    break
  fi
done &
