---
- name: Install packages
  hosts: all
  become: true
  become_user: root
  become_method: ansible.builtin.su
  gather_facts: false
  vars_files:
    vars.yml

  tasks:
    - name: Install packages
      register: result
      ansible.builtin.apt:
        pkg: "{{ packages }}"
        state: present
        update_cache: true

    - name: Print
      ansible.builtin.debug:
        msg: '{{ result }}'
